### ISSUE TITLE
stroke-dashoffset Infinite Linear Animation Lag

### ISSUE THREAD

**Issue by burgil** [sketchpunk/NEditorJS#5]
Hey @sketchpunk and everyone else,

I tried ShaderBlocks the other day, and loved that animations, and so I'm now trying to enable these animations on NEditorJS since it's less complex to work with, but I found a weird bug I would like help solving please:

Every 30 seconds the animation lags (tried other intervals, same same new name, also it should only affect speed since it's set to infinite linear)

I attached a full test that I've made (: https://vimeo.com/675896726/fe03a1e87a

```css
@keyframes moveDashOffset{
  from{ stroke-dashoffset: 500; }
  to{ stroke-dashoffset: 0; }
}
path{
  animation: moveDashOffset 30s linear infinite;
}
----------------------------------------------------------
@keyframes path-move {
  from {
    stroke-dashoffset: 0%;
  }
  to {
    stroke-dashoffset: 100%;
  }
}

path{
  animation: path-move 30s infinite linear;
}
----------------------------------------------------------
@keyframes path-move-reverse {
  to {
    stroke-dashoffset: 0%;
  }
  from {
    stroke-dashoffset: 100%;
  }
}

path{
  animation: path-move-reverse 30s infinite linear;
}
```
None of the solutions above work properly :/

Any other solution will be highly appreciated!

Thanks for the helpers!

Also can you please add a license file for us to work with please? ✋

**Comment by burgil** [comment]
I seem to have solved my own problem, I hate when it happens (;
Trial and error got it eventually, as long as you never give up, it will work:
```css
path {
  stroke-dasharray: 10;
  animation: path-move 5s infinite linear;
  stroke-dashoffset: 100;
}

@keyframes path-move {
  to {
    stroke-dashoffset: 0;
  }
}
```
Leave the `stroke-dasharray` at 10 and `animation` length at 5s as it seems to be the perfect combo, the speed is controlled via `stroke-dashoffset`, eg, 100 = slow and 1000 = fast
make sure `stroke-dashoffset` is rounded by 10, I think, Still testing, Values that worked: `100, 200, 300, 400, 1000` (which is all the values I tested)

**Comment by burgil** [comment]
Armed with what I learned on Mozilla docs, I've also made a variation that works with offsets:
```css
path {
  stroke-dasharray: 10, 5, 10;
  animation: flow 5s infinite linear;
  stroke-dashoffset: 100;
}

@keyframes flow {
  to {
    stroke-dashoffset: 0;
  }
}
```
Original offset: `stroke-dasharray: 20, 5, 5, 5, 5, 5;`
